### ISSUE TITLE
Add filter by project issues

### ISSUE THREAD

**Issue by rbugajewski** [ande3577/redmine-stuff-to-do-plugin#28]
The current filter just shows a list of projects. It would be very helpful to see all open / whatever issues from a single project. I think that adding a separate drop down is the way to go.

**Comment by ande3577** [comment]
I agree that the filter implementation is very poor (my only defence being that it was like that when I got there).

If it is going to be reworked, I would suggest using the interface from the issues page. This would allow far more power and flexibility that simply adding a drop down list to select a project.

**Comment by rbugajewski** [comment]
Yes, this is indeed a better solution. I just wanted to offer a quick-and-dirty solution, because integrating an issues-like interface will be technically harder to implement.
