### ISSUE TITLE
Issues row color Inverted

### ISSUE THREAD

**Issue by easly1989** [ande3577/redmine-stuff-to-do-plugin#31]
![image](https://f.cloud.github.com/assets/3910202/338401/7c208d44-9d10-11e2-818c-fabf42c71579.png)
![image](https://f.cloud.github.com/assets/3910202/338402/840c20b8-9d10-11e2-857e-d293e9838bc2.png)
As you can see from the screenshot it seems to work, but the truth is that all the red issues have priority "Normal" and all the white issues are "Urgent"..

any suggestion?

**Comment by easly1989** [comment]
Reopening this, as the issue seems to be ralated to the css
infact it takes the priority-LEVEL at position column in the enumeration table.
But in redmine 2.3.0 the priority-LEVEL is equal to the enumertion id column.

to make it correct you should change the css to work with the new standard

**Comment by ande3577** [comment]
Can you test the fix on branch _exp/31_fix_stylesheet_ and see if that fixes it?

**Comment by easly1989** [comment]
yep working good now :)
thanks ande :)

**Comment by ande3577** [comment]
It is now merged into master.

Thanks for the find.
