### ISSUE TITLE
Issues assigned to groups

### ISSUE THREAD

**Issue by easly1989** [ande3577/redmine-stuff-to-do-plugin#32]
Hello there,
While i was testing the plugin i noticed that it actually doesn't adds to the user the issues that are assigned to a group (even if the user is part of it)

do you think this is a bug or a future feature you can implement?

i would like to implement this anyway and i'll search for a solution while waiting for your answer

thanks in advance

**Comment by easly1989** [comment]
i've modified the stuff_to_do.rb model (in app/models) as follows

``` ruby
def self.conditions_for_available(user, filter_by, project)
  scope = self
  conditions = "#{IssueStatus.table_name}.is_closed = false"
  conditions << " AND (" << "#{Project.table_name}.status = %d" % [Project::STATUS_ACTIVE] << ")"
  conditions << " AND (" << "assigned_to_id = %d" % [user.id] << ")"
  user.group_ids.each do |groupid|
    conditions << " OR (" << "assigned_to_id = %d" % [groupid] << ")"
  end
  case 
  when filter_by.is_a?(IssueStatus), filter_by.is_a?(Enumeration)
    table_name = filter_by.class.table_name
    conditions << " AND (" << "#{table_name}.id = (%d)" % [filter_by.id] << ")"
  end
  conditions << ( " AND (" << "#{Issue.table_name}.project_id = %d" % [project.id] << ")" ) unless project.nil?
  conditions
  end
end
```

adding this lines:

``` ruby
user.group_ids.each do |groupid|
  conditions << " OR (" << "assigned_to_id = %d" % [groupid] << ")"
end
```

It seems to work, but i'm not as experienced as you, so i'll wait for your opinion about it.. 
anyway i'm able to add and remove issue from the left panes..
let me know what you think :)

**Comment by ande3577** [comment]
Can now see issues assigned via group in stuff to do, however adding to stuff to do via issue page or context menu results in 404.
