### ISSUE TITLE
Feature : Show only commons project

### ISSUE THREAD

**Issue by lspg** [ande3577/redmine-stuff-to-do-plugin#36]
At the moment, activating the permission "View others stuff to do" allows the user to see the full project list of the "managed" user, even the projects the "manager" isn't involved in.

It would be nice to have either : 
- A new permission allowing to show
  - the full user's project list
  - or a filtered list with only the projects both the managed user and the manager are involved in.
- Or a config page like the one made for managing the reportees, allowing to choose wich projects to show for each user activated in the reportees.

Couldn't help much as i'm a total ruby noob, but very nice work you made here.

**Comment by cforce** [comment]
Yes this is usefuly for e.g developers being in different projects and beeing managed by different project lead, where as every project leader  manages the developer in different projects.
+1

**Comment by ande3577** [comment]
Thanks, I'd like to take credit for the nice work, but 99% of it is inherited.

Question regarding this feature:  What would you propose for the tasks that a user is currently being shown?

**Comment by lspg** [comment]
I think the manager should see all the managed user's issues, as long as they belong to a project the manager is involved in.
The manager doesn't have to be watching the managed user's issues to see them in the list.

Don't know if this sounds clear and if it answers your question ?
