### ISSUE TITLE
personal detailed work time (mass) time caturing

### ISSUE THREAD

**Issue by cforce** [ande3577/redmine-stuff-to-do-plugin#38]
Start,stop,pause and resume time on issues you are working one,

example: 
http://i2.wp.com/blog.goyello.com/wp-content/uploads/2009/09/StuffToDo_Smaller.jpg?resize=721%2C246
http://i1.wp.com/blog.goyello.com/wp-content/uploads/2009/09/StuffTodo_4_play_pause_cancel.jpg?resize=521%2C95
http://i2.wp.com/blog.goyello.com/wp-content/uploads/2009/09/StuffTodo_6_quick_log.jpg?resize=523%2C324
http://i1.wp.com/blog.goyello.com/wp-content/uploads/2009/09/StuffTodo_5_mass_log.jpg?resize=464%2C474

The idea comes from a firk also of eric davis plugin, which was great but no more mainatianed. Maybe you can integrate their code and make it work for redmine 2.3
see https://github.com/GOYELLO/goyello_stuff_to_do/network
http://blog.goyello.com/2009/09/11/we-all-have-to-register-time-but-why-bother/

**Comment by ande3577** [comment]
I am currently using my fork of the [time tracker plugin](https://github.com/ande3577/redmine_time_tracker) which achieves this from the issue page or context menu.
