### ISSUE TITLE
Compatibility with 2.3.x

### ISSUE THREAD

**Issue by zenmedia** [ande3577/redmine-stuff-to-do-plugin#41]
Hi,

When trying to get this working with redmine 2.3.x i have found that the top menu items produce a 404, and also the same for the "configure" link on the plugin page.

When i did finally get the pages to display after much "hacking" with the code, it was horribly broken. (probably due to the fact i am crap at ruby).

Are there currently any plans to provide compatibility with 2.3.x?

**Comment by ande3577** [comment]
2.3 should work as i am running it on a production instance of 2.3.2.

check to make sure the plugin is located at _plugins/stuff_to_do_plugin_.

**Comment by zenmedia** [comment]
Hi, Please accept my apologies, we had an older copy of the plugin which was causing database conflicts and it was "tested" from github project from the original developer. I just found your branch and wanted to check first before i broke anything. ;)
