### ISSUE TITLE
Unable to select another assignee than me even I'm the manager on projects

### ISSUE THREAD

**Issue by kraklin** [ande3577/redmine-stuff-to-do-plugin#44]
Hi,

first thanks for great job. This is first stuff-to-do-plugin branch that works with Redmine version 2.3.1. Thank you for that.

However I can only see my tasks but I'm unable to see others task nor assign task order for them. Iˇm Redmine adminitstrator and manager on several projects. 

Do you know where can be the problem or what I'm doing wrong?

Thanks

**Comment by ande3577** [comment]
Is there a user drop down item on your stuff to do page?
If this drop down is there, is there a list of available users present? Or is the task list for other users simply empty?
Lastly, do the users you are trying to manage have the stuff to do plugin enabled in their account settings.

**Comment by kraklin** [comment]
Thanks,

I didn't know that there is any option in my account page. After checking View All Reportee everything is working. Sorry for this silly question and keep up the good work ;)
