### ISSUE TITLE
Template::Error (undefined method `include?' for nil:NilClass) ->FIX: DEFAULT Plugin Settings 

### ISSUE THREAD

**Issue by cforce** [ande3577/redmine-stuff-to-do-plugin#48]
The latest changes produces errors when i open an issue

Template::Error (undefined method `include?' for nil:NilClass):
    2:   <% assigned_to = @issue.assigned_to %>
    3:   <% assigned_to = User.current if assigned_to.is_a?(Group) && User.current.is_or_belongs_to?(assigned_to) %>
    4:  <% if !assigned_to.nil? && assigned_to.is_a?(User) && (assigned_to == User.current || User.current.allowed_to?(:view_others_stuff_to_do, nil, :global => true)) %>
    5:      <% if StuffToDo.available(assigned_to, @project, assigned_to).count(@issue) > 0 %>
    6:              <div id="stuff-to-do">
    7:              <% if assigned_to == User.current %>
    8:               <p><h3><%=l(:stuff_to_do_title)%></h3>
  lib/redmine/hook.rb:111:in`block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in`each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in`tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:158:in`call_hook'
  app/views/issues/_sidebar.html.erb:17:in `_app_views_issues__sidebar_html_erb___1053293041_124235650'
  app/views/issues/show.html.erb:144:in`block in _app_views_issues_show_html_erb___251933713_113790350'
  app/helpers/application_helper.rb:1149:in `content_for'
  app/views/issues/show.html.erb:143:in`_app_views_issues_show_html_erb___251933713_113790350'
  app/controllers/issues_controller.rb:119:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:116:in`show'

**Comment by cforce** [comment]
I analysed and found out that "StuffToDo.available(assigned_to, @project, assigned_to)" evaluates to nil
in views/stuff_to_do/_view_issues_sidebar_queries_bottom.html.erb

**Comment by cforce** [comment]
The null pointer raises deeper in stuff_to_do model line 82,
then in conditions_for_available()  --> unless Setting.plugin_stuff_to_do_plugin['statuses_for_stuff_to_do'].include? 'all'

It looks like the work around is to set first the setting "Statuses available as Stuff To Do Items".

It shall be default set to "All Open statuses" , so there is no exception!

**Comment by nkavian** [comment]
Just spent 2 hours figuring out the same.

**Comment by ande3577** [comment]
Finally had a chance to look at this.  Should be fixed in: 11bbf0b5ee7ca3e5585c4c317bdc65595a1e3216
